-- Verified 2026-2027 Term 1 timetable and teacher assignments.
-- Source: جدول المعلمين سبتمبر 2027.pdf plus the provided verified assignment and 12-week files.
-- Quran, Swimming and PE remain in the timetable with fixed parent-facing text,
-- but are deliberately excluded from teacher assignments and plan-submission gates.

begin;

insert into public.subjects (code, name_en, name_ar, parent_plan_name, department_id, minimum_grade, maximum_grade, include_in_weekly_plan, is_active)
select source.code, source.name_en, source.name_ar, source.parent_plan_name, department.id, source.minimum_grade, source.maximum_grade, source.include_in_weekly_plan, true
from (values
  ('arabic', 'Arabic', 'اللغة العربية', 'Arabic', 'arabic_social', 1, 10, True),
  ('quran', 'Quran', 'القرآن الكريم', 'Quran', 'arabic_social', 1, 10, False),
  ('islamic', 'Islamic Studies', 'التربية الإسلامية', 'Islamic Studies', 'arabic_social', 1, 10, True),
  ('social', 'Social Studies', 'الدراسات الاجتماعية', 'Social Studies', 'arabic_social', 4, 9, True),
  ('history', 'History', 'التاريخ', 'History', 'arabic_social', 10, 10, True),
  ('philosophy', 'Philosophy', 'الفلسفة', 'Philosophy', 'arabic_social', 10, 10, True),
  ('english_al', 'English AL', 'اللغة الإنجليزية AL', 'English', 'english', 1, 10, True),
  ('english_ol', 'English OL', 'اللغة الإنجليزية OL', 'English', 'english', 1, 10, True),
  ('french', 'French', 'اللغة الفرنسية', 'French', 'english', 5, 10, True),
  ('math', 'Mathematics', 'الرياضيات', 'Mathematics', 'math_science', 1, 10, True),
  ('science', 'Science', 'العلوم', 'Science', 'math_science', 1, 9, True),
  ('integrated_science', 'Integrated Science', 'العلوم المتكاملة', 'Integrated Science', 'math_science', 10, 10, True),
  ('ict', 'ICT', 'تقنية المعلومات', 'ICT', 'ict', 1, 10, True),
  ('computer', 'Computer', 'الحاسب', 'Computer', 'ict', 1, 3, True),
  ('ai', 'AI', 'الذكاء الاصطناعي', 'AI', 'ict', 3, 8, True),
  ('pe', 'PE', 'التربية البدنية', 'PE', 'pe', 1, 10, False),
  ('art', 'Art', 'التربية الفنية', 'Art', 'art', 1, 10, True),
  ('handwriting', 'Handwriting', 'الخط', 'Handwriting', 'arabic_social', 1, 3, True),
  ('swimming', 'Swimming', 'السباحة', 'Swimming', 'swimming', 1, 6, False)
) as source(code, name_en, name_ar, parent_plan_name, department_code, minimum_grade, maximum_grade, include_in_weekly_plan)
join public.departments department on department.code = source.department_code
on conflict (code) do update set
  name_en = excluded.name_en,
  name_ar = excluded.name_ar,
  parent_plan_name = excluded.parent_plan_name,
  department_id = excluded.department_id,
  minimum_grade = excluded.minimum_grade,
  maximum_grade = excluded.maximum_grade,
  include_in_weekly_plan = excluded.include_in_weekly_plan,
  is_active = true;

-- Replace the 17-week calendar with the verified 12 teaching weeks.
delete from public.academic_weeks
where academic_year = '2026-2027'
  and week_number > 12;

update public.academic_weeks set is_current = false
where academic_year = '2026-2027';

insert into public.academic_weeks (academic_year, week_number, starts_on, ends_on, label, is_current)
values
  ('2026-2027', 1, '2026-09-06'::date, '2026-09-10'::date, 'Week 1', true),
  ('2026-2027', 2, '2026-09-13'::date, '2026-09-17'::date, 'Week 2', false),
  ('2026-2027', 3, '2026-09-20'::date, '2026-09-24'::date, 'Week 3', false),
  ('2026-2027', 4, '2026-09-27'::date, '2026-10-01'::date, 'Week 4', false),
  ('2026-2027', 5, '2026-10-04'::date, '2026-10-08'::date, 'Week 5', false),
  ('2026-2027', 6, '2026-10-11'::date, '2026-10-15'::date, 'Week 6', false),
  ('2026-2027', 7, '2026-10-18'::date, '2026-10-22'::date, 'Week 7', false),
  ('2026-2027', 8, '2026-10-25'::date, '2026-10-29'::date, 'Week 8', false),
  ('2026-2027', 9, '2026-11-01'::date, '2026-11-05'::date, 'Week 9', false),
  ('2026-2027', 10, '2026-11-08'::date, '2026-11-12'::date, 'Week 10', false),
  ('2026-2027', 11, '2026-11-15'::date, '2026-11-19'::date, 'Week 11', false),
  ('2026-2027', 12, '2026-11-22'::date, '2026-11-26'::date, 'Week 12', false)
on conflict (academic_year, week_number) do update set
  starts_on = excluded.starts_on,
  ends_on = excluded.ends_on,
  label = excluded.label,
  is_current = excluded.is_current;

-- A controlled username map avoids guessing from Arabic display names.
create temporary table verified_teacher_usernames (source_teacher text primary key, username text not null) on commit drop;
insert into verified_teacher_usernames (source_teacher, username) values
  ('ابو العلا', 'waelaboeleal'),
  ('ابو شادي', 'uaboshadi'),
  ('احمد حسن', 'ahmed.hassan2030'),
  ('اسامة', 'osamaselim78'),
  ('الجزار', 'esam'),
  ('النمر', 'mmohamed'),
  ('بدر', 'mohamed-1972'),
  ('بكر', 'mohamedsayed7974'),
  ('جمال', 'gabdulhameed'),
  ('حلمي', 'mhelmy'),
  ('حمد', 'm.mhamad'),
  ('سالم', 'amabrouk'),
  ('سعيد', 'msaid'),
  ('شعبان', 'mohamedshaban'),
  ('شكري', 'waelshokry'),
  ('عبدالحميد', 'm.abdelhameed'),
  ('عبدالناصر', 'akhlil2277'),
  ('عثمان', 'mohasay012345'),
  ('عدس', 'mr.ahmedads'),
  ('علي بدير', 'aabuzaid1973'),
  ('عمرو', 'amrrezk'),
  ('فريد', 'mrmahmd'),
  ('فودة', 'mfouda'),
  ('مؤمن', 'moamen'),
  ('ماجد', 'maged.h.mousa'),
  ('محمد سمير', 'msamir'),
  ('مدكور', 'madkour'),
  ('ممدوح', '0592089734');

-- Fail atomically if an expected staff account is not active.
do $$
declare missing_usernames text;
begin
  select string_agg(map.username, ', ' order by map.username)
  into missing_usernames
  from verified_teacher_usernames map
  left join public.profiles profile on profile.username = map.username and profile.status = 'active'
  where profile.user_id is null;
  if missing_usernames is not null then
    raise exception 'Missing active teacher accounts: %', missing_usernames;
  end if;
end $$;

create temporary table verified_timetable_source (
  class_code text not null,
  subject_label text not null,
  teacher_username text,
  day_of_week integer not null,
  period_number integer not null,
  requires_weekly_plan_submission boolean not null,
  primary key (class_code, day_of_week, period_number)
) on commit drop;

insert into verified_timetable_source values
  ('3/A', 'عربي', 'mohamedshaban', 0, 6, true),
  ('3/A', 'عربي', 'mohamedshaban', 0, 5, true),
  ('3/B', 'عربي', 'mohamedshaban', 0, 4, true),
  ('4/B', 'قرأن', null, 0, 2, false),
  ('3/B', 'دين', 'mohamedshaban', 0, 1, true),
  ('3/B', 'عربي', 'mohamedshaban', 1, 8, true),
  ('3/B', 'عربي', 'mohamedshaban', 1, 7, true),
  ('3/A', 'عربي', 'mohamedshaban', 1, 6, true),
  ('3/A', 'دين', 'mohamedshaban', 1, 4, true),
  ('4/B', 'قرأن', null, 1, 2, false),
  ('3/B', 'دين', 'mohamedshaban', 1, 1, true),
  ('3/B', 'عربي', 'mohamedshaban', 2, 7, true),
  ('3/B', 'عربي', 'mohamedshaban', 2, 6, true),
  ('3/A', 'عربي', 'mohamedshaban', 2, 5, true),
  ('3/A', 'عربي', 'mohamedshaban', 2, 4, true),
  ('3/B', 'دين', 'mohamedshaban', 2, 3, true),
  ('4/B', 'قرأن', null, 2, 2, false),
  ('3/A', 'عربي', 'mohamedshaban', 3, 8, true),
  ('3/A', 'عربي', 'mohamedshaban', 3, 7, true),
  ('3/B', 'عربي', 'mohamedshaban', 3, 4, true),
  ('3/B', 'عربي', 'mohamedshaban', 3, 3, true),
  ('4/B', 'قرأن', null, 3, 2, false),
  ('3/A', 'دين', 'mohamedshaban', 3, 1, true),
  ('3/B', 'عربي', 'mohamedshaban', 4, 7, true),
  ('3/B', 'عربي', 'mohamedshaban', 4, 6, true),
  ('3/A', 'عربي', 'mohamedshaban', 4, 5, true),
  ('3/A', 'عربي', 'mohamedshaban', 4, 4, true),
  ('3/A', 'دين', 'mohamedshaban', 4, 3, true),
  ('4/B', 'قرأن', null, 4, 2, false),
  ('4/B', 'عربي', 'm.mhamad', 0, 8, true),
  ('4/B', 'دين', 'm.mhamad', 0, 6, true),
  ('4/A', 'عربي', 'm.mhamad', 0, 5, true),
  ('4/A', 'قرأن', null, 0, 2, false),
  ('4/A', 'عربي', 'm.mhamad', 0, 1, true),
  ('4/B', 'عربي', 'm.mhamad', 1, 8, true),
  ('4/A', 'عربي', 'm.mhamad', 1, 7, true),
  ('4/A', 'عربي', 'm.mhamad', 1, 3, true),
  ('4/A', 'قرأن', null, 1, 2, false),
  ('4/B', 'عربي', 'm.mhamad', 1, 1, true),
  ('4/B', 'عربي', 'm.mhamad', 2, 6, true),
  ('4/A', 'عربي', 'm.mhamad', 2, 5, true),
  ('4/B', 'عربي', 'm.mhamad', 2, 3, true),
  ('4/A', 'قرأن', null, 2, 2, false),
  ('4/A', 'عربي', 'm.mhamad', 2, 1, true),
  ('4/B', 'دين', 'm.mhamad', 3, 8, true),
  ('4/A', 'عربي', 'm.mhamad', 3, 4, true),
  ('4/A', 'دين', 'm.mhamad', 3, 3, true),
  ('4/A', 'قرأن', null, 3, 2, false),
  ('4/B', 'عربي', 'm.mhamad', 3, 1, true),
  ('4/B', 'عربي', 'm.mhamad', 4, 7, true),
  ('4/A', 'دين', 'm.mhamad', 4, 6, true),
  ('4/B', 'عربي', 'm.mhamad', 4, 3, true),
  ('4/A', 'قرأن', null, 4, 2, false),
  ('4/A', 'عربي', 'm.mhamad', 4, 1, true),
  ('6/A', 'عربي', 'maged.h.mousa', 0, 8, true),
  ('6/A', 'دين', 'maged.h.mousa', 0, 7, true),
  ('6/B', 'عربي', 'maged.h.mousa', 0, 6, true),
  ('6/A', 'عربي', 'maged.h.mousa', 0, 5, true),
  ('6/B', 'عربي', 'maged.h.mousa', 0, 4, true),
  ('6/A', 'قرأن', null, 0, 2, false),
  ('6/A', 'عربي', 'maged.h.mousa', 1, 6, true),
  ('2/A', 'دين', 'maged.h.mousa', 1, 5, true),
  ('6/A', 'قرأن', null, 1, 2, false),
  ('6/B', 'عربي', 'maged.h.mousa', 1, 1, true),
  ('6/B', 'عربي', 'maged.h.mousa', 2, 7, true),
  ('6/B', 'دين', 'maged.h.mousa', 2, 6, true),
  ('6/A', 'دين', 'maged.h.mousa', 2, 5, true),
  ('6/A', 'عربي', 'maged.h.mousa', 2, 4, true),
  ('6/A', 'قرأن', null, 2, 2, false),
  ('2/A', 'دين', 'maged.h.mousa', 2, 1, true),
  ('6/B', 'دين', 'maged.h.mousa', 3, 8, true),
  ('6/A', 'عربي', 'maged.h.mousa', 3, 7, true),
  ('6/A', 'عربي', 'maged.h.mousa', 3, 6, true),
  ('6/B', 'عربي', 'maged.h.mousa', 3, 4, true),
  ('6/B', 'عربي', 'maged.h.mousa', 3, 3, true),
  ('6/A', 'قرأن', null, 3, 2, false),
  ('6/B', 'عربي', 'maged.h.mousa', 4, 8, true),
  ('2/A', 'دين', 'maged.h.mousa', 4, 5, true),
  ('6/A', 'عربي', 'maged.h.mousa', 4, 4, true),
  ('6/B', 'عربي', 'maged.h.mousa', 4, 3, true),
  ('6/A', 'قرأن', null, 4, 2, false),
  ('6/A', 'عربي', 'maged.h.mousa', 4, 1, true),
  ('8/A', 'عربي', 'mohamedsayed7974', 0, 8, true),
  ('8/A', 'دين', 'mohamedsayed7974', 0, 7, true),
  ('8/B', 'عربي', 'mohamedsayed7974', 0, 6, true),
  ('8/A', 'عربي', 'mohamedsayed7974', 0, 4, true),
  ('8/A', 'قرأن', null, 0, 2, false),
  ('1/B', 'دين', 'mohamedsayed7974', 0, 1, true),
  ('8/A', 'عربي', 'mohamedsayed7974', 1, 8, true),
  ('8/B', 'عربي', 'mohamedsayed7974', 1, 5, true),
  ('8/A', 'قرأن', null, 1, 2, false),
  ('8/A', 'عربي', 'mohamedsayed7974', 1, 1, true),
  ('8/A', 'عربي', 'mohamedsayed7974', 2, 8, true),
  ('8/B', 'دين', 'mohamedsayed7974', 2, 7, true),
  ('8/B', 'عربي', 'mohamedsayed7974', 2, 4, true),
  ('8/A', 'عربي', 'mohamedsayed7974', 2, 3, true),
  ('8/A', 'قرأن', null, 2, 2, false),
  ('8/A', 'عربي', 'mohamedsayed7974', 3, 5, true),
  ('1/B', 'دين', 'mohamedsayed7974', 3, 4, true),
  ('8/B', 'دين', 'mohamedsayed7974', 3, 3, true),
  ('8/A', 'قرأن', null, 3, 2, false),
  ('8/B', 'عربي', 'mohamedsayed7974', 3, 1, true),
  ('8/B', 'عربي', 'mohamedsayed7974', 4, 8, true),
  ('8/B', 'عربي', 'mohamedsayed7974', 4, 6, true),
  ('1/B', 'دين', 'mohamedsayed7974', 4, 4, true),
  ('8/A', 'دين', 'mohamedsayed7974', 4, 3, true),
  ('8/A', 'قرأن', null, 4, 2, false),
  ('8/B', 'عربي', 'mohamedsayed7974', 4, 1, true),
  ('9/A', 'عربي', 'mfouda', 0, 8, true),
  ('9/A', 'عربي', 'mfouda', 0, 6, true),
  ('9/B', 'عربي', 'mfouda', 0, 1, true),
  ('9/A', 'عربي', 'mfouda', 1, 8, true),
  ('9/A', 'دين', 'mfouda', 1, 4, true),
  ('9/B', 'عربي', 'mfouda', 1, 3, true),
  ('9/A', 'عربي', 'mfouda', 2, 8, true),
  ('9/B', 'عربي', 'mfouda', 2, 6, true),
  ('9/B', 'دين', 'mfouda', 2, 4, true),
  ('9/B', 'عربي', 'mfouda', 2, 3, true),
  ('9/A', 'عربي', 'mfouda', 3, 8, true),
  ('9/B', 'عربي', 'mfouda', 3, 7, true),
  ('9/B', 'دين', 'mfouda', 3, 6, true),
  ('9/B', 'عربي', 'mfouda', 3, 3, true),
  ('10/A', 'دين', 'mfouda', 3, 1, true),
  ('9/A', 'عربي', 'mfouda', 4, 8, true),
  ('9/A', 'دين', 'mfouda', 4, 6, true),
  ('10/A', 'دين', 'mfouda', 4, 5, true),
  ('9/B', 'عربي', 'mfouda', 4, 3, true),
  ('9/A', 'عربي', 'mfouda', 4, 1, true),
  ('1/B', 'عربي', 'amabrouk', 0, 8, true),
  ('1/B', 'عربي', 'amabrouk', 0, 7, true),
  ('1/A', 'عربي', 'amabrouk', 0, 4, true),
  ('1/A', 'قرأن', null, 0, 2, false),
  ('1/A', 'عربي', 'amabrouk', 0, 1, true),
  ('1/A', 'عربي', 'amabrouk', 1, 8, true),
  ('1/A', 'عربي', 'amabrouk', 1, 7, true),
  ('1/B', 'عربي', 'amabrouk', 1, 6, true),
  ('1/B', 'عربي', 'amabrouk', 1, 5, true),
  ('1/A', 'دين', 'amabrouk', 1, 4, true),
  ('1/A', 'قرأن', null, 1, 2, false),
  ('1/A', 'عربي', 'amabrouk', 2, 8, true),
  ('1/A', 'عربي', 'amabrouk', 2, 7, true),
  ('1/B', 'عربي', 'amabrouk', 2, 6, true),
  ('1/B', 'عربي', 'amabrouk', 2, 5, true),
  ('1/A', 'دين', 'amabrouk', 2, 3, true),
  ('1/A', 'قرأن', null, 2, 2, false),
  ('1/A', 'عربي', 'amabrouk', 3, 7, true),
  ('1/A', 'عربي', 'amabrouk', 3, 6, true),
  ('1/B', 'عربي', 'amabrouk', 3, 3, true),
  ('1/A', 'قرأن', null, 3, 2, false),
  ('1/B', 'عربي', 'amabrouk', 4, 8, true),
  ('1/B', 'عربي', 'amabrouk', 4, 7, true),
  ('1/A', 'عربي', 'amabrouk', 4, 6, true),
  ('1/A', 'قرأن', null, 4, 2, false),
  ('1/A', 'دين', 'amabrouk', 4, 1, true),
  ('9/B', 'دراسات', 'esam', 0, 7, true),
  ('7/A', 'دراسات', 'esam', 0, 6, true),
  ('8/A', 'دراسات', 'esam', 0, 5, true),
  ('6/B', 'دراسات', 'esam', 0, 3, true),
  ('6/A', 'دراسات', 'esam', 0, 1, true),
  ('7/B', 'دراسات', 'esam', 1, 7, true),
  ('8/B', 'دراسات', 'esam', 1, 6, true),
  ('6/A', 'دراسات', 'esam', 1, 5, true),
  ('9/A', 'دراسات', 'esam', 1, 1, true),
  ('6/A', 'دراسات', 'esam', 2, 8, true),
  ('7/A', 'دراسات', 'esam', 2, 6, true),
  ('9/B', 'دراسات', 'esam', 2, 5, true),
  ('7/B', 'دراسات', 'esam', 2, 4, true),
  ('9/A', 'دراسات', 'esam', 2, 3, true),
  ('7/A', 'دراسات', 'esam', 3, 8, true),
  ('6/B', 'دراسات', 'esam', 3, 7, true),
  ('8/A', 'دراسات', 'esam', 3, 6, true),
  ('8/B', 'دراسات', 'esam', 3, 5, true),
  ('9/A', 'دراسات', 'esam', 3, 3, true),
  ('8/A', 'دراسات', 'esam', 4, 8, true),
  ('9/B', 'دراسات', 'esam', 4, 6, true),
  ('6/B', 'دراسات', 'esam', 4, 5, true),
  ('8/B', 'دراسات', 'esam', 4, 4, true),
  ('7/B', 'دراسات', 'esam', 4, 3, true),
  ('10/A', 'تاريخ', 'waelshokry', 0, 6, true),
  ('4/A', 'دراسات', 'waelshokry', 0, 4, true),
  ('5/A', 'دراسات', 'waelshokry', 0, 3, true),
  ('3/B', 'قرأن', null, 0, 2, false),
  ('5/B', 'دراسات', 'waelshokry', 0, 1, true),
  ('10/A', 'تاريخ', 'waelshokry', 1, 5, true),
  ('4/B', 'دراسات', 'waelshokry', 1, 4, true),
  ('3/B', 'قرأن', null, 1, 2, false),
  ('4/A', 'دراسات', 'waelshokry', 2, 8, true),
  ('5/B', 'دراسات', 'waelshokry', 2, 7, true),
  ('4/B', 'دراسات', 'waelshokry', 2, 5, true),
  ('10/A', 'فلسفة', 'waelshokry', 2, 3, true),
  ('3/B', 'قرأن', null, 2, 2, false),
  ('5/A', 'دراسات', 'waelshokry', 2, 1, true),
  ('5/A', 'دراسات', 'waelshokry', 3, 7, true),
  ('5/B', 'دراسات', 'waelshokry', 3, 6, true),
  ('4/B', 'دراسات', 'waelshokry', 3, 3, true),
  ('3/B', 'قرأن', null, 3, 2, false),
  ('5/B', 'دراسات', 'waelshokry', 4, 8, true),
  ('4/A', 'دراسات', 'waelshokry', 4, 7, true),
  ('5/A', 'دراسات', 'waelshokry', 4, 5, true),
  ('10/A', 'فلسفة', 'waelshokry', 4, 3, true),
  ('3/B', 'قرأن', null, 4, 2, false),
  ('4/A', 'Maths', 'uaboshadi', 0, 6, true),
  ('8/B', 'Maths', 'uaboshadi', 0, 4, true),
  ('3/B', 'Maths', 'uaboshadi', 0, 3, true),
  ('3/A', 'Maths', 'uaboshadi', 0, 1, true),
  ('4/A', 'Maths', 'uaboshadi', 1, 8, true),
  ('8/B', 'Maths', 'uaboshadi', 1, 7, true),
  ('3/A', 'Maths', 'uaboshadi', 1, 5, true),
  ('8/A', 'Maths', 'uaboshadi', 1, 4, true),
  ('3/B', 'Maths', 'uaboshadi', 1, 3, true),
  ('8/A', 'Maths', 'uaboshadi', 2, 6, true),
  ('3/B', 'Maths', 'uaboshadi', 2, 5, true),
  ('4/A', 'Maths', 'uaboshadi', 2, 4, true),
  ('3/A', 'Maths', 'uaboshadi', 2, 1, true),
  ('8/B', 'Maths', 'uaboshadi', 3, 8, true),
  ('3/B', 'Maths', 'uaboshadi', 3, 5, true),
  ('8/A', 'Maths', 'uaboshadi', 3, 4, true),
  ('3/A', 'Maths', 'uaboshadi', 3, 3, true),
  ('4/A', 'Maths', 'uaboshadi', 3, 1, true),
  ('3/A', 'Maths', 'uaboshadi', 4, 8, true),
  ('8/B', 'Maths', 'uaboshadi', 4, 7, true),
  ('8/A', 'Maths', 'uaboshadi', 4, 6, true),
  ('4/A', 'Maths', 'uaboshadi', 4, 5, true),
  ('3/B', 'Maths', 'uaboshadi', 4, 4, true),
  ('9/B', 'Maths', '0592089734', 0, 8, true),
  ('9/A', 'Maths', '0592089734', 0, 7, true),
  ('10/A', 'Maths', '0592089734', 0, 5, true),
  ('2/A', 'Maths', '0592089734', 0, 4, true),
  ('4/B', 'Maths', '0592089734', 0, 3, true),
  ('3/A', 'قرأن', null, 0, 2, false),
  ('10/A', 'Maths', '0592089734', 1, 6, true),
  ('9/B', 'Maths', '0592089734', 1, 4, true),
  ('4/B', 'Maths', '0592089734', 1, 3, true),
  ('3/A', 'قرأن', null, 1, 2, false),
  ('2/A', 'Maths', '0592089734', 1, 1, true),
  ('2/A', 'Maths', '0592089734', 2, 8, true),
  ('10/A', 'Maths', '0592089734', 2, 7, true),
  ('9/A', 'Maths', '0592089734', 2, 5, true),
  ('3/A', 'قرأن', null, 2, 2, false),
  ('4/B', 'Maths', '0592089734', 2, 1, true),
  ('4/B', 'Maths', '0592089734', 3, 7, true),
  ('10/A', 'Maths', '0592089734', 3, 6, true),
  ('9/A', 'Maths', '0592089734', 3, 5, true),
  ('9/B', 'Maths', '0592089734', 3, 4, true),
  ('3/A', 'قرأن', null, 3, 2, false),
  ('2/A', 'Maths', '0592089734', 3, 1, true),
  ('9/B', 'Maths', '0592089734', 4, 7, true),
  ('10/A', 'Maths', '0592089734', 4, 6, true),
  ('9/A', 'Maths', '0592089734', 4, 4, true),
  ('2/A', 'Maths', '0592089734', 4, 3, true),
  ('3/A', 'قرأن', null, 4, 2, false),
  ('4/B', 'Maths', '0592089734', 4, 1, true),
  ('5/A', 'Maths', 'mr.ahmedads', 0, 8, true),
  ('7/A', 'Maths', 'mr.ahmedads', 0, 7, true),
  ('6/A', 'Maths', 'mr.ahmedads', 0, 4, true),
  ('5/B', 'Maths', 'mr.ahmedads', 0, 3, true),
  ('6/B', 'Maths', 'mr.ahmedads', 0, 1, true),
  ('6/B', 'Maths', 'mr.ahmedads', 1, 7, true),
  ('7/B', 'Maths', 'mr.ahmedads', 1, 4, true),
  ('7/A', 'Maths', 'mr.ahmedads', 1, 3, true),
  ('5/A', 'Maths', 'mr.ahmedads', 1, 1, true),
  ('7/A', 'Maths', 'mr.ahmedads', 2, 8, true),
  ('5/B', 'Maths', 'mr.ahmedads', 2, 6, true),
  ('7/B', 'Maths', 'mr.ahmedads', 2, 5, true),
  ('5/A', 'Maths', 'mr.ahmedads', 2, 4, true),
  ('6/A', 'Maths', 'mr.ahmedads', 2, 1, true),
  ('5/A', 'Maths', 'mr.ahmedads', 3, 8, true),
  ('6/B', 'Maths', 'mr.ahmedads', 3, 5, true),
  ('5/B', 'Maths', 'mr.ahmedads', 3, 4, true),
  ('7/B', 'Maths', 'mr.ahmedads', 3, 3, true),
  ('6/A', 'Maths', 'mr.ahmedads', 3, 1, true),
  ('7/B', 'Maths', 'mr.ahmedads', 4, 7, true),
  ('6/B', 'Maths', 'mr.ahmedads', 4, 6, true),
  ('5/B', 'Maths', 'mr.ahmedads', 4, 5, true),
  ('7/A', 'Maths', 'mr.ahmedads', 4, 4, true),
  ('6/A', 'Maths', 'mr.ahmedads', 4, 3, true),
  ('2/A', 'AL', 'm.abdelhameed', 0, 8, true),
  ('2/A', 'AL', 'm.abdelhameed', 0, 7, true),
  ('1/B', 'AL', 'm.abdelhameed', 0, 4, true),
  ('1/A', 'AL', 'm.abdelhameed', 0, 3, true),
  ('1/B', 'AL', 'm.abdelhameed', 1, 8, true),
  ('1/B', 'AL', 'm.abdelhameed', 1, 7, true),
  ('1/A', 'AL', 'm.abdelhameed', 1, 6, true),
  ('2/A', 'AL', 'm.abdelhameed', 1, 4, true),
  ('1/A', 'AL', 'm.abdelhameed', 1, 3, true),
  ('1/B', 'AL', 'm.abdelhameed', 1, 1, true),
  ('1/B', 'OL', 'm.abdelhameed', 2, 8, true),
  ('2/A', 'AL', 'm.abdelhameed', 2, 6, true),
  ('1/A', 'AL', 'm.abdelhameed', 2, 4, true),
  ('1/B', 'AL', 'm.abdelhameed', 2, 3, true),
  ('1/A', 'AL', 'm.abdelhameed', 2, 1, true),
  ('1/A', 'OL', 'm.abdelhameed', 3, 8, true),
  ('1/B', 'OL', 'm.abdelhameed', 3, 6, true),
  ('1/A', 'OL', 'm.abdelhameed', 3, 5, true),
  ('1/A', 'OL', 'm.abdelhameed', 3, 4, true),
  ('1/B', 'OL', 'm.abdelhameed', 3, 1, true),
  ('1/A', 'OL', 'm.abdelhameed', 4, 8, true),
  ('1/B', 'OL', 'm.abdelhameed', 4, 5, true),
  ('1/A', 'OL', 'm.abdelhameed', 4, 4, true),
  ('1/B', 'OL', 'm.abdelhameed', 4, 3, true),
  ('2/A', 'AL', 'm.abdelhameed', 4, 1, true),
  ('8/A', 'OL', 'osamaselim78', 0, 6, true),
  ('8/B', 'OL', 'osamaselim78', 0, 5, true),
  ('5/A', 'AL', 'osamaselim78', 0, 4, true),
  ('8/B', 'OL', 'osamaselim78', 0, 3, true),
  ('5/A', 'OL', 'osamaselim78', 0, 1, true),
  ('5/A', 'OL', 'osamaselim78', 1, 6, true),
  ('8/A', 'OL', 'osamaselim78', 1, 5, true),
  ('8/A', 'AL', 'osamaselim78', 1, 3, true),
  ('8/B', 'AL', 'osamaselim78', 1, 1, true),
  ('5/A', 'AL', 'osamaselim78', 2, 7, true),
  ('8/B', 'AL', 'osamaselim78', 2, 6, true),
  ('8/A', 'OL', 'osamaselim78', 2, 5, true),
  ('8/B', 'OL', 'osamaselim78', 2, 3, true),
  ('8/A', 'AL', 'osamaselim78', 2, 1, true),
  ('8/A', 'AL', 'osamaselim78', 3, 7, true),
  ('8/B', 'AL', 'osamaselim78', 3, 6, true),
  ('5/A', 'OL', 'osamaselim78', 3, 5, true),
  ('8/B', 'OL', 'osamaselim78', 3, 4, true),
  ('5/A', 'AL', 'osamaselim78', 3, 1, true),
  ('5/A', 'AL', 'osamaselim78', 4, 7, true),
  ('8/A', 'AL', 'osamaselim78', 4, 5, true),
  ('5/A', 'OL', 'osamaselim78', 4, 4, true),
  ('8/B', 'AL', 'osamaselim78', 4, 3, true),
  ('8/A', 'OL', 'osamaselim78', 4, 1, true),
  ('6/B', 'OL', 'amrrezk', 0, 8, true),
  ('6/A', 'OL', 'amrrezk', 0, 6, true),
  ('10/A', 'OL', 'amrrezk', 0, 3, true),
  ('10/A', 'AL', 'amrrezk', 0, 1, true),
  ('10/A', 'OL', 'amrrezk', 1, 8, true),
  ('6/A', 'OL', 'amrrezk', 1, 7, true),
  ('6/B', 'AL', 'amrrezk', 1, 6, true),
  ('6/B', 'AL', 'amrrezk', 1, 5, true),
  ('10/A', 'AL', 'amrrezk', 1, 1, true),
  ('10/A', 'OL', 'amrrezk', 2, 8, true),
  ('6/A', 'AL', 'amrrezk', 2, 7, true),
  ('10/A', 'AL', 'amrrezk', 2, 6, true),
  ('6/A', 'AL', 'amrrezk', 2, 3, true),
  ('6/B', 'OL', 'amrrezk', 2, 1, true),
  ('6/A', 'OL', 'amrrezk', 3, 8, true),
  ('6/B', 'OL', 'amrrezk', 3, 6, true),
  ('6/A', 'AL', 'amrrezk', 3, 5, true),
  ('10/A', 'AL', 'amrrezk', 3, 4, true),
  ('6/B', 'AL', 'amrrezk', 3, 1, true),
  ('10/A', 'OL', 'amrrezk', 4, 8, true),
  ('6/A', 'OL', 'amrrezk', 4, 7, true),
  ('6/A', 'AL', 'amrrezk', 4, 5, true),
  ('6/B', 'OL', 'amrrezk', 4, 4, true),
  ('6/B', 'AL', 'amrrezk', 4, 1, true),
  ('7/B', 'OL', 'mohamed-1972', 0, 8, true),
  ('9/B', 'AL', 'mohamed-1972', 0, 6, true),
  ('7/B', 'AL', 'mohamed-1972', 0, 5, true),
  ('9/B', 'OL', 'mohamed-1972', 0, 4, true),
  ('9/A', 'OL', 'mohamed-1972', 0, 3, true),
  ('9/A', 'AL', 'mohamed-1972', 0, 1, true),
  ('7/B', 'AL', 'mohamed-1972', 1, 8, true),
  ('9/B', 'OL', 'mohamed-1972', 1, 5, true),
  ('9/A', 'OL', 'mohamed-1972', 1, 3, true),
  ('9/B', 'AL', 'mohamed-1972', 1, 1, true),
  ('7/B', 'AL', 'mohamed-1972', 2, 8, true),
  ('9/A', 'AL', 'mohamed-1972', 2, 7, true),
  ('7/B', 'OL', 'mohamed-1972', 2, 6, true),
  ('9/A', 'OL', 'mohamed-1972', 2, 4, true),
  ('9/B', 'OL', 'mohamed-1972', 2, 1, true),
  ('9/B', 'AL', 'mohamed-1972', 3, 8, true),
  ('9/A', 'AL', 'mohamed-1972', 3, 7, true),
  ('9/A', 'OL', 'mohamed-1972', 3, 6, true),
  ('7/B', 'OL', 'mohamed-1972', 3, 5, true),
  ('7/B', 'AL', 'mohamed-1972', 4, 8, true),
  ('9/B', 'OL', 'mohamed-1972', 4, 5, true),
  ('9/B', 'AL', 'mohamed-1972', 4, 4, true),
  ('9/A', 'AL', 'mohamed-1972', 4, 3, true),
  ('7/B', 'OL', 'mohamed-1972', 4, 1, true),
  ('4/A', 'Science', 'gabdulhameed', 0, 7, true),
  ('4/B', 'Science', 'gabdulhameed', 0, 4, true),
  ('6/B', 'قرأن', null, 0, 2, false),
  ('9/A', 'Science', 'gabdulhameed', 1, 7, true),
  ('9/B', 'Science', 'gabdulhameed', 1, 6, true),
  ('6/B', 'قرأن', null, 1, 2, false),
  ('9/B', 'Science', 'gabdulhameed', 2, 8, true),
  ('4/B', 'Science', 'gabdulhameed', 2, 7, true),
  ('4/A', 'Science', 'gabdulhameed', 2, 6, true),
  ('6/B', 'قرأن', null, 2, 2, false),
  ('9/A', 'Science', 'gabdulhameed', 2, 1, true),
  ('4/A', 'Science', 'gabdulhameed', 3, 7, true),
  ('9/A', 'Science', 'gabdulhameed', 3, 4, true),
  ('6/B', 'قرأن', null, 3, 2, false),
  ('9/B', 'Science', 'gabdulhameed', 3, 1, true),
  ('9/A', 'Science', 'gabdulhameed', 4, 7, true),
  ('4/B', 'Science', 'gabdulhameed', 4, 5, true),
  ('6/B', 'قرأن', null, 4, 2, false),
  ('9/B', 'Science', 'gabdulhameed', 4, 1, true),
  ('10/A', 'INT Science', 'akhlil2277', 0, 7, true),
  ('5/A', 'Science', 'akhlil2277', 0, 6, true),
  ('6/B', 'Science', 'akhlil2277', 0, 5, true),
  ('6/A', 'Science', 'akhlil2277', 0, 3, true),
  ('7/A', 'قرأن', null, 0, 2, false),
  ('8/B', 'Science', 'akhlil2277', 0, 1, true),
  ('6/A', 'Science', 'akhlil2277', 1, 8, true),
  ('8/A', 'Science', 'akhlil2277', 1, 6, true),
  ('5/A', 'Science', 'akhlil2277', 1, 5, true),
  ('10/A', 'INT Science', 'akhlil2277', 1, 4, true),
  ('8/B', 'Science', 'akhlil2277', 1, 3, true),
  ('7/A', 'قرأن', null, 1, 2, false),
  ('5/B', 'Science', 'akhlil2277', 1, 1, true),
  ('8/A', 'Science', 'akhlil2277', 2, 7, true),
  ('5/A', 'Science', 'akhlil2277', 2, 5, true),
  ('6/B', 'Science', 'akhlil2277', 2, 4, true),
  ('7/A', 'قرأن', null, 2, 2, false),
  ('10/A', 'INT Science', 'akhlil2277', 2, 1, true),
  ('5/B', 'Science', 'akhlil2277', 3, 8, true),
  ('8/B', 'Science', 'akhlil2277', 3, 7, true),
  ('6/A', 'Science', 'akhlil2277', 3, 4, true),
  ('10/A', 'INT Science', 'akhlil2277', 3, 3, true),
  ('7/A', 'قرأن', null, 3, 2, false),
  ('8/A', 'Science', 'akhlil2277', 3, 1, true),
  ('6/B', 'Science', 'akhlil2277', 4, 7, true),
  ('8/B', 'Science', 'akhlil2277', 4, 5, true),
  ('8/A', 'Science', 'akhlil2277', 4, 4, true),
  ('5/B', 'Science', 'akhlil2277', 4, 3, true),
  ('7/A', 'قرأن', null, 4, 2, false),
  ('8/B', 'AI', 'madkour', 0, 8, true),
  ('7/B', 'AI', 'madkour', 0, 4, true),
  ('10/A', 'قرأن', null, 0, 2, false),
  ('8/A', 'AI', 'madkour', 0, 1, true),
  ('9/B', 'ICT', 'madkour', 1, 8, true),
  ('9/B', 'ICT', 'madkour', 1, 7, true),
  ('9/A', 'ICT', 'madkour', 1, 6, true),
  ('9/A', 'ICT', 'madkour', 1, 5, true),
  ('10/A', 'قرأن', null, 1, 2, false),
  ('7/B', 'ICT', 'madkour', 2, 7, true),
  ('7/A', 'ICT', 'madkour', 2, 3, true),
  ('10/A', 'قرأن', null, 2, 2, false),
  ('8/B', 'ICT', 'madkour', 2, 1, true),
  ('3/B', 'حاسب', 'madkour', 3, 7, true),
  ('3/A', 'AI', 'madkour', 3, 4, true),
  ('7/A', 'AI', 'madkour', 3, 3, true),
  ('10/A', 'قرأن', null, 3, 2, false),
  ('8/A', 'ICT', 'madkour', 4, 7, true),
  ('3/B', 'ICT', 'madkour', 4, 5, true),
  ('10/A', 'ICT', 'madkour', 4, 4, true),
  ('10/A', 'قرأن', null, 4, 2, false),
  ('3/A', 'ICT', 'madkour', 4, 1, true),
  ('5/B', 'فنية', 'aabuzaid1973', 0, 7, true),
  ('9/B', 'فنية', 'aabuzaid1973', 0, 5, true),
  ('8/A', 'فنية', 'aabuzaid1973', 0, 3, true),
  ('8/B', 'قرأن', null, 0, 2, false),
  ('6/B', 'فنية', 'aabuzaid1973', 1, 8, true),
  ('3/B', 'فنية', 'aabuzaid1973', 1, 6, true),
  ('1/A', 'خط', 'aabuzaid1973', 1, 5, true),
  ('4/A', 'فنية', 'aabuzaid1973', 1, 4, true),
  ('3/A', 'خط', 'aabuzaid1973', 1, 3, true),
  ('8/B', 'قرأن', null, 1, 2, false),
  ('3/A', 'فنية', 'aabuzaid1973', 2, 8, true),
  ('9/A', 'فنية', 'aabuzaid1973', 2, 6, true),
  ('8/B', 'فنية', 'aabuzaid1973', 2, 5, true),
  ('1/B', 'خط', 'aabuzaid1973', 2, 4, true),
  ('8/B', 'قرأن', null, 2, 2, false),
  ('1/B', 'فنية', 'aabuzaid1973', 2, 1, true),
  ('2/A', 'خط', 'aabuzaid1973', 3, 8, true),
  ('3/B', 'خط', 'aabuzaid1973', 3, 6, true),
  ('5/A', 'فنية', 'aabuzaid1973', 3, 4, true),
  ('2/A', 'فنية', 'aabuzaid1973', 3, 3, true),
  ('8/B', 'قرأن', null, 3, 2, false),
  ('7/B', 'فنية', 'aabuzaid1973', 3, 1, true),
  ('6/A', 'فنية', 'aabuzaid1973', 4, 8, true),
  ('7/A', 'فنية', 'aabuzaid1973', 4, 6, true),
  ('1/A', 'فنية', 'aabuzaid1973', 4, 5, true),
  ('4/B', 'فنية', 'aabuzaid1973', 4, 4, true),
  ('8/B', 'قرأن', null, 4, 2, false),
  ('3/B', 'سباحة', null, 0, 8, false),
  ('3/B', 'سباحة', null, 0, 7, false),
  ('1/A', 'سباحة', null, 0, 6, false),
  ('1/A', 'سباحة', null, 0, 5, false),
  ('5/A', 'سباحة', null, 1, 8, false),
  ('5/A', 'سباحة', null, 1, 7, false),
  ('6/B', 'سباحة', null, 1, 4, false),
  ('6/B', 'سباحة', null, 1, 3, false),
  ('4/A', 'AL', 'mrmahmd', 0, 8, true),
  ('4/B', 'AL', 'mrmahmd', 0, 7, true),
  ('5/B', 'AL', 'mrmahmd', 0, 6, true),
  ('4/A', 'OL', 'mrmahmd', 0, 3, true),
  ('5/A', 'قرأن', null, 0, 2, false),
  ('4/B', 'OL', 'mrmahmd', 1, 7, true),
  ('5/B', 'AL', 'mrmahmd', 1, 6, true),
  ('5/A', 'قرأن', null, 1, 2, false),
  ('4/A', 'AL', 'mrmahmd', 1, 1, true),
  ('4/B', 'OL', 'mrmahmd', 2, 8, true),
  ('5/B', 'AL', 'mrmahmd', 2, 5, true),
  ('4/B', 'AL', 'mrmahmd', 2, 4, true),
  ('4/A', 'AL', 'mrmahmd', 2, 3, true),
  ('5/A', 'قرأن', null, 2, 2, false),
  ('4/A', 'OL', 'mrmahmd', 3, 8, true),
  ('4/B', 'OL', 'mrmahmd', 3, 6, true),
  ('4/A', 'OL', 'mrmahmd', 3, 5, true),
  ('4/B', 'AL', 'mrmahmd', 3, 4, true),
  ('5/A', 'قرأن', null, 3, 2, false),
  ('4/B', 'OL', 'mrmahmd', 4, 8, true),
  ('5/B', 'AL', 'mrmahmd', 4, 7, true),
  ('4/B', 'AL', 'mrmahmd', 4, 6, true),
  ('4/A', 'AL', 'mrmahmd', 4, 4, true),
  ('4/A', 'OL', 'mrmahmd', 4, 3, true),
  ('5/A', 'قرأن', null, 4, 2, false),
  ('10/A', 'French', 'mmohamed', 0, 8, true),
  ('7/A', 'French', 'mmohamed', 0, 5, true),
  ('9/A', 'French', 'mmohamed', 0, 4, true),
  ('7/B', 'French', 'mmohamed', 0, 3, true),
  ('9/A', 'قرأن', null, 0, 2, false),
  ('7/B', 'French', 'mmohamed', 0, 1, true),
  ('7/A', 'French', 'mmohamed', 1, 8, true),
  ('8/A', 'French', 'mmohamed', 1, 7, true),
  ('8/B', 'French', 'mmohamed', 1, 4, true),
  ('9/A', 'قرأن', null, 1, 2, false),
  ('8/B', 'French', 'mmohamed', 2, 8, true),
  ('6/B', 'French', 'mmohamed', 2, 3, true),
  ('9/A', 'قرأن', null, 2, 2, false),
  ('8/A', 'French', 'mmohamed', 3, 8, true),
  ('9/B', 'French', 'mmohamed', 3, 5, true),
  ('6/A', 'French', 'mmohamed', 3, 3, true),
  ('9/A', 'قرأن', null, 3, 2, false),
  ('9/A', 'French', 'mmohamed', 3, 1, true),
  ('9/B', 'French', 'mmohamed', 4, 8, true),
  ('10/A', 'French', 'mmohamed', 4, 7, true),
  ('5/B', 'French', 'mmohamed', 4, 6, true),
  ('5/A', 'French', 'mmohamed', 4, 3, true),
  ('9/A', 'قرأن', null, 4, 2, false),
  ('1/B', 'سباحة', null, 0, 6, false),
  ('1/B', 'سباحة', null, 0, 5, false),
  ('5/B', 'سباحة', null, 1, 8, false),
  ('5/B', 'سباحة', null, 1, 7, false),
  ('4/A', 'سباحة', null, 1, 6, false),
  ('4/A', 'سباحة', null, 1, 5, false),
  ('7/A', 'بدنية', null, 0, 8, false),
  ('8/B', 'بدنية', null, 0, 7, false),
  ('9/A', 'بدنية', null, 0, 5, false),
  ('9/B', 'بدنية', null, 0, 3, false),
  ('5/B', 'قرأن', null, 0, 2, false),
  ('4/B', 'بدنية', null, 0, 1, false),
  ('8/B', 'بدنية', null, 1, 8, false),
  ('7/B', 'بدنية', null, 1, 6, false),
  ('7/A', 'بدنية', null, 1, 4, false),
  ('10/A', 'بدنية', null, 1, 3, false),
  ('5/B', 'قرأن', null, 1, 2, false),
  ('6/B', 'بدنية', null, 2, 8, false),
  ('9/B', 'بدنية', null, 2, 7, false),
  ('8/A', 'بدنية', null, 2, 4, false),
  ('3/A', 'بدنية', null, 2, 3, false),
  ('5/B', 'قرأن', null, 2, 2, false),
  ('7/B', 'بدنية', null, 3, 8, false),
  ('10/A', 'بدنية', null, 3, 7, false),
  ('5/A', 'بدنية', null, 3, 6, false),
  ('8/A', 'بدنية', null, 3, 3, false),
  ('5/B', 'قرأن', null, 3, 2, false),
  ('5/B', 'بدنية', null, 3, 1, false),
  ('4/A', 'بدنية', null, 4, 8, false),
  ('6/A', 'بدنية', null, 4, 6, false),
  ('9/A', 'بدنية', null, 4, 5, false),
  ('5/B', 'قرأن', null, 4, 2, false),
  ('3/B', 'بدنية', null, 4, 1, false),
  ('7/B', 'عربي', 'msaid', 0, 7, true),
  ('5/A', 'دين', 'msaid', 0, 5, true),
  ('7/A', 'دين', 'msaid', 0, 4, true),
  ('7/B', 'قرأن', null, 0, 2, false),
  ('7/A', 'عربي', 'msaid', 0, 1, true),
  ('7/A', 'عربي', 'msaid', 1, 6, true),
  ('7/B', 'دين', 'msaid', 1, 5, true),
  ('5/A', 'دين', 'msaid', 1, 4, true),
  ('5/B', 'دين', 'msaid', 1, 3, true),
  ('7/B', 'قرأن', null, 1, 2, false),
  ('7/B', 'عربي', 'msaid', 1, 1, true),
  ('7/A', 'عربي', 'msaid', 2, 7, true),
  ('7/A', 'عربي', 'msaid', 2, 5, true),
  ('5/B', 'دين', 'msaid', 2, 4, true),
  ('7/B', 'عربي', 'msaid', 2, 3, true),
  ('7/B', 'قرأن', null, 2, 2, false),
  ('7/B', 'عربي', 'msaid', 2, 1, true),
  ('7/B', 'عربي', 'msaid', 3, 7, true),
  ('7/A', 'دين', 'msaid', 3, 6, true),
  ('7/A', 'عربي', 'msaid', 3, 5, true),
  ('7/B', 'عربي', 'msaid', 3, 4, true),
  ('7/B', 'قرأن', null, 3, 2, false),
  ('7/A', 'عربي', 'msaid', 4, 7, true),
  ('7/B', 'دين', 'msaid', 4, 6, true),
  ('7/B', 'عربي', 'msaid', 4, 4, true),
  ('7/B', 'قرأن', null, 4, 2, false),
  ('7/A', 'عربي', 'msaid', 4, 1, true),
  ('6/B', 'AI', 'msamir', 0, 7, true),
  ('4/B', 'AI', 'msamir', 0, 5, true),
  ('2/A', 'ICT', 'msamir', 0, 3, true),
  ('5/B', 'AI', 'msamir', 1, 4, true),
  ('1/B', 'ICT', 'msamir', 1, 3, true),
  ('6/A', 'AI', 'msamir', 1, 1, true),
  ('5/A', 'AI', 'msamir', 2, 8, true),
  ('4/A', 'AI', 'msamir', 2, 7, true),
  ('6/A', 'ICT', 'msamir', 2, 6, true),
  ('6/B', 'ICT', 'msamir', 2, 5, true),
  ('1/B', 'حاسب', 'msamir', 3, 8, true),
  ('4/A', 'ICT', 'msamir', 3, 6, true),
  ('4/B', 'ICT', 'msamir', 3, 5, true),
  ('5/B', 'ICT', 'msamir', 3, 3, true),
  ('1/A', 'ICT', 'msamir', 3, 1, true),
  ('2/A', 'حاسب', 'msamir', 4, 8, true),
  ('5/A', 'ICT', 'msamir', 4, 6, true),
  ('1/A', 'حاسب', 'msamir', 4, 3, true),
  ('3/A', 'سباحة', null, 0, 8, false),
  ('3/A', 'سباحة', null, 0, 7, false),
  ('2/A', 'سباحة', null, 0, 6, false),
  ('2/A', 'سباحة', null, 0, 5, false),
  ('4/B', 'سباحة', null, 1, 6, false),
  ('4/B', 'سباحة', null, 1, 5, false),
  ('6/A', 'سباحة', null, 1, 4, false),
  ('6/A', 'سباحة', null, 1, 3, false),
  ('5/B', 'OL', 'mhelmy', 0, 5, true),
  ('7/A', 'AL', 'mhelmy', 0, 3, true),
  ('7/A', 'OL', 'mhelmy', 1, 7, true),
  ('7/A', 'AL', 'mhelmy', 1, 1, true),
  ('5/B', 'OL', 'mhelmy', 2, 3, true),
  ('7/A', 'OL', 'mhelmy', 2, 1, true),
  ('7/A', 'OL', 'mhelmy', 3, 7, true),
  ('5/B', 'OL', 'mhelmy', 3, 5, true),
  ('7/A', 'AL', 'mhelmy', 3, 1, true),
  ('7/A', 'AL', 'mhelmy', 4, 5, true),
  ('7/A', 'OL', 'mhelmy', 4, 3, true),
  ('5/B', 'OL', 'mhelmy', 4, 1, true),
  ('1/A', 'Maths', 'waelaboeleal', 0, 8, true),
  ('1/A', 'Science', 'waelaboeleal', 0, 7, true),
  ('7/B', 'Science', 'waelaboeleal', 0, 6, true),
  ('3/A', 'Science', 'waelaboeleal', 0, 4, true),
  ('1/B', 'Maths', 'waelaboeleal', 0, 3, true),
  ('2/A', 'Science', 'waelaboeleal', 1, 8, true),
  ('7/A', 'Science', 'waelaboeleal', 1, 5, true),
  ('1/B', 'Maths', 'waelaboeleal', 1, 4, true),
  ('7/B', 'Science', 'waelaboeleal', 1, 3, true),
  ('1/A', 'Maths', 'waelaboeleal', 1, 1, true),
  ('1/B', 'Maths', 'waelaboeleal', 2, 7, true),
  ('1/A', 'Maths', 'waelaboeleal', 2, 5, true),
  ('7/A', 'Science', 'waelaboeleal', 2, 4, true),
  ('3/B', 'Science', 'waelaboeleal', 2, 1, true),
  ('7/B', 'Science', 'waelaboeleal', 3, 6, true),
  ('1/B', 'Maths', 'waelaboeleal', 3, 5, true),
  ('7/A', 'Science', 'waelaboeleal', 3, 4, true),
  ('1/A', 'Maths', 'waelaboeleal', 3, 3, true),
  ('7/A', 'Science', 'waelaboeleal', 4, 8, true),
  ('1/A', 'Maths', 'waelaboeleal', 4, 7, true),
  ('1/B', 'Maths', 'waelaboeleal', 4, 6, true),
  ('7/B', 'Science', 'waelaboeleal', 4, 5, true),
  ('1/B', 'Science', 'waelaboeleal', 4, 1, true),
  ('3/B', 'AL', 'moamen', 0, 6, true),
  ('3/B', 'OL', 'moamen', 0, 5, true),
  ('3/A', 'OL', 'moamen', 0, 3, true),
  ('2/A', 'قرأن', null, 0, 2, false),
  ('3/A', 'OL', 'moamen', 1, 8, true),
  ('3/A', 'AL', 'moamen', 1, 7, true),
  ('3/B', 'OL', 'moamen', 1, 5, true),
  ('3/B', 'AL', 'moamen', 1, 4, true),
  ('2/A', 'OL', 'moamen', 1, 3, true),
  ('2/A', 'قرأن', null, 1, 2, false),
  ('3/A', 'AL', 'moamen', 1, 1, true),
  ('3/B', 'OL', 'moamen', 2, 8, true),
  ('3/A', 'OL', 'moamen', 2, 7, true),
  ('3/A', 'AL', 'moamen', 2, 6, true),
  ('3/B', 'AL', 'moamen', 2, 4, true),
  ('2/A', 'OL', 'moamen', 2, 3, true),
  ('2/A', 'قرأن', null, 2, 2, false),
  ('3/B', 'AL', 'moamen', 3, 8, true),
  ('2/A', 'OL', 'moamen', 3, 7, true),
  ('3/A', 'AL', 'moamen', 3, 6, true),
  ('3/A', 'OL', 'moamen', 3, 5, true),
  ('2/A', 'OL', 'moamen', 3, 4, true),
  ('2/A', 'قرأن', null, 3, 2, false),
  ('3/B', 'OL', 'moamen', 3, 1, true),
  ('3/B', 'OL', 'moamen', 4, 8, true),
  ('3/A', 'OL', 'moamen', 4, 7, true),
  ('3/A', 'AL', 'moamen', 4, 6, true),
  ('2/A', 'OL', 'moamen', 4, 4, true),
  ('3/B', 'AL', 'moamen', 4, 3, true),
  ('2/A', 'قرأن', null, 4, 2, false),
  ('5/B', 'عربي', 'ahmed.hassan2030', 0, 8, true),
  ('5/A', 'عربي', 'ahmed.hassan2030', 0, 7, true),
  ('5/B', 'عربي', 'ahmed.hassan2030', 0, 4, true),
  ('1/B', 'قرأن', null, 0, 2, false),
  ('2/A', 'عربي', 'ahmed.hassan2030', 0, 1, true),
  ('2/A', 'عربي', 'ahmed.hassan2030', 1, 7, true),
  ('2/A', 'عربي', 'ahmed.hassan2030', 1, 6, true),
  ('5/B', 'عربي', 'ahmed.hassan2030', 1, 5, true),
  ('5/A', 'عربي', 'ahmed.hassan2030', 1, 3, true),
  ('1/B', 'قرأن', null, 1, 2, false),
  ('5/B', 'عربي', 'ahmed.hassan2030', 2, 8, true),
  ('5/A', 'عربي', 'ahmed.hassan2030', 2, 6, true),
  ('2/A', 'عربي', 'ahmed.hassan2030', 2, 5, true),
  ('2/A', 'عربي', 'ahmed.hassan2030', 2, 4, true),
  ('5/A', 'عربي', 'ahmed.hassan2030', 2, 3, true),
  ('1/B', 'قرأن', null, 2, 2, false),
  ('5/B', 'عربي', 'ahmed.hassan2030', 2, 1, true),
  ('5/B', 'عربي', 'ahmed.hassan2030', 3, 7, true),
  ('2/A', 'عربي', 'ahmed.hassan2030', 3, 6, true),
  ('2/A', 'عربي', 'ahmed.hassan2030', 3, 5, true),
  ('5/A', 'عربي', 'ahmed.hassan2030', 3, 3, true),
  ('1/B', 'قرأن', null, 3, 2, false),
  ('5/A', 'عربي', 'ahmed.hassan2030', 4, 8, true),
  ('2/A', 'عربي', 'ahmed.hassan2030', 4, 7, true),
  ('2/A', 'عربي', 'ahmed.hassan2030', 4, 6, true),
  ('5/B', 'عربي', 'ahmed.hassan2030', 4, 4, true),
  ('1/B', 'قرأن', null, 4, 2, false),
  ('5/A', 'عربي', 'ahmed.hassan2030', 4, 1, true),
  ('2/A', 'بدنية', null, 2, 7, false),
  ('1/A', 'بدنية', null, 2, 6, false),
  ('1/B', 'بدنية', null, 3, 7, false),
  ('10/A', 'عربي', 'mohasay012345', 0, 4, true),
  ('9/B', 'قرأن', null, 0, 2, false),
  ('10/A', 'عربي', 'mohasay012345', 1, 7, true),
  ('9/B', 'قرأن', null, 1, 2, false),
  ('10/A', 'عربي', 'mohasay012345', 2, 5, true),
  ('10/A', 'عربي', 'mohasay012345', 2, 4, true),
  ('9/B', 'قرأن', null, 2, 2, false),
  ('10/A', 'عربي', 'mohasay012345', 3, 8, true),
  ('10/A', 'عربي', 'mohasay012345', 3, 5, true),
  ('9/B', 'قرأن', null, 3, 2, false),
  ('9/B', 'قرأن', null, 4, 2, false),
  ('10/A', 'عربي', 'mohasay012345', 4, 1, true);

-- Remove only assignments for the accounts governed by this verified source.
delete from public.teacher_assignments assignment
using public.profiles profile
where assignment.teacher_id = profile.user_id
  and profile.username in (select username from verified_teacher_usernames);

insert into public.teacher_assignments (teacher_id, class_id, subject_id)
select distinct profile.user_id, school_class.id, subject_record.id
from verified_timetable_source source
join public.school_classes school_class on concat(school_class.grade, '/', school_class.section) = source.class_code
join public.subjects subject_record on subject_record.name_ar = case source.subject_label
  when 'عربي' then 'اللغة العربية' when 'قرأن' then 'القرآن الكريم' when 'دين' then 'التربية الإسلامية'
  when 'دراسات' then 'الدراسات الاجتماعية' when 'تاريخ' then 'التاريخ' when 'فلسفة' then 'الفلسفة'
  when 'AL' then 'اللغة الإنجليزية AL' when 'OL' then 'اللغة الإنجليزية OL' when 'French' then 'اللغة الفرنسية'
  when 'Maths' then 'الرياضيات' when 'Science' then 'العلوم' when 'INT Science' then 'العلوم المتكاملة'
  when 'ICT' then 'تقنية المعلومات' when 'حاسب' then 'الحاسب' when 'AI' then 'الذكاء الاصطناعي'
  when 'فنية' then 'التربية الفنية' when 'خط' then 'الخط' else null end
join public.profiles profile on profile.username = source.teacher_username and profile.status = 'active'
where source.requires_weekly_plan_submission
on conflict (teacher_id, class_id, subject_id) do nothing;

-- Replace the full 18-class timetable with all 720 verified lesson slots.
delete from public.timetable_slots
where class_id in (select id from public.school_classes where grade between 1 and 10 and section in ('A', 'B'));

insert into public.timetable_slots (class_id, subject_id, teacher_id, day_of_week, period_number, requires_weekly_plan_submission)
select school_class.id, subject_record.id, profile.user_id, source.day_of_week, source.period_number, source.requires_weekly_plan_submission
from verified_timetable_source source
join public.school_classes school_class on concat(school_class.grade, '/', school_class.section) = source.class_code
join public.subjects subject_record on subject_record.name_ar = case source.subject_label
  when 'عربي' then 'اللغة العربية' when 'قرأن' then 'القرآن الكريم' when 'دين' then 'التربية الإسلامية'
  when 'دراسات' then 'الدراسات الاجتماعية' when 'تاريخ' then 'التاريخ' when 'فلسفة' then 'الفلسفة'
  when 'AL' then 'اللغة الإنجليزية AL' when 'OL' then 'اللغة الإنجليزية OL' when 'French' then 'اللغة الفرنسية'
  when 'Maths' then 'الرياضيات' when 'Science' then 'العلوم' when 'INT Science' then 'العلوم المتكاملة'
  when 'ICT' then 'تقنية المعلومات' when 'حاسب' then 'الحاسب' when 'AI' then 'الذكاء الاصطناعي'
  when 'بدنية' then 'التربية البدنية' when 'فنية' then 'التربية الفنية' when 'خط' then 'الخط' when 'سباحة' then 'السباحة' end
left join public.profiles profile on profile.username = source.teacher_username and profile.status = 'active';

-- Publication is automatic when every required timetable slot has non-empty work.
create or replace function private.refresh_weekly_plan_publication_state(target_plan_id uuid)
returns boolean
language plpgsql
security definer
set search_path = ''
as $$
declare plan_is_ready boolean := false;
begin
  select exists (
    select 1 from public.timetable_slots slot
    join public.weekly_plans plan on plan.class_id = slot.class_id
    where plan.id = target_plan_id and slot.requires_weekly_plan_submission
  ) and not exists (
    select 1 from public.timetable_slots slot
    join public.weekly_plans plan on plan.class_id = slot.class_id
    where plan.id = target_plan_id and slot.requires_weekly_plan_submission
      and not exists (
        select 1 from public.plan_entries entry
        where entry.weekly_plan_id = target_plan_id
          and entry.timetable_slot_id = slot.id
          and entry.teacher_id = slot.teacher_id
          and entry.subject_id = slot.subject_id
          and btrim(coalesce(entry.classwork, '')) <> ''
      )
  ) into plan_is_ready;

  update public.weekly_plans
  set status = case when plan_is_ready then 'published' else 'draft' end,
      published_at = case when plan_is_ready then coalesce(published_at, now()) else null end,
      updated_at = now()
  where id = target_plan_id;
  return coalesce(plan_is_ready, false);
end;
$$;

create or replace function private.refresh_publication_after_plan_entry()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if tg_op = 'DELETE' then
    perform private.refresh_weekly_plan_publication_state(old.weekly_plan_id);
    return old;
  end if;
  perform private.refresh_weekly_plan_publication_state(new.weekly_plan_id);
  return new;
end;
$$;

drop trigger if exists refresh_publication_after_plan_entry on public.plan_entries;
create trigger refresh_publication_after_plan_entry
after insert or update or delete on public.plan_entries
for each row execute function private.refresh_publication_after_plan_entry();

drop policy if exists "Public reads published plan entries" on public.plan_entries;
create policy "Public reads published plan entries" on public.plan_entries for select to anon
using (exists (select 1 from public.weekly_plans plan where plan.id = plan_entries.weekly_plan_id and plan.status = 'published'));

drop policy if exists "Public reads published quizzes" on public.plan_quizzes;
create policy "Public reads published quizzes" on public.plan_quizzes for select to anon
using (exists (select 1 from public.weekly_plans plan where plan.id = plan_quizzes.weekly_plan_id and plan.status = 'published'));

drop policy if exists "Public reads published notes" on public.plan_notes;
create policy "Public reads published notes" on public.plan_notes for select to anon
using (exists (select 1 from public.weekly_plans plan where plan.id = plan_notes.weekly_plan_id and plan.status = 'published'));

commit;
